#! /bin/sh
sudo cpufreq-set --min 800MHz --max 1.4GHz -c 0 -g 'powersave'
sudo cpufreq-set --min 800MHz --max 1.4GHz -c 1 -g 'powersave'
sudo cpufreq-set --min 800MHz --max 1.4GHz -c 2 -g 'powersave'
sudo cpufreq-set --min 800MHz --max 1.4GHz -c 3 -g 'powersave'
